# import psycopg
# from psycopg import sql
# from pg_database.pg_connection import get_connection


# with get_connection() as conn:
#     cur = conn.cursor()
#     # cur.execute("""CREATE TABLE IF NOT EXISTS test (
#     #             id INT GENERATED BY DEFAUT AS IDENTITY PRIMARY KEY,)
#     #             name VARCHAR(20) NOT NULL,
#     #             age INT,
#     #             """)


#     query = sql.SQL("""INSERT INTO {} ({}) VALUES (%s, %s)""").format(
#         sql.Identifier('''t'es"t'''),
#         sql.SQL(', ').join([sql.Identifier('name'), sql.Identifier('age')]))
#     print(query.as_string())

#     # cur.execute(query, ['mat', 20])

# import psycopg
# from pg_modules.pg_connection import get_connection

# with get_connection() as conn:
#     print(conn.execute('SELECT * FROM tag').fetchall())
# conn.close()
# conn.close()

print(len('this is my really long username'))