CREATE EXTENSION IF NOT EXISTS pgcrypto; -- for gen_random_uuid()

CREATE TYPE account_type AS ENUM ('admin','main_cashier','cashier');
CREATE TYPE transaction_type AS ENUM ('purchase','deposit','withdrawal');
CREATE TYPE account_change_type AS ENUM ('username','password_hash');


-- // metadata / reference_id / notes
-- // Enforce username uniqueness using lower(username) and a partial index so soft-deleted accounts don’t collide.
-- // Add indexes on tag_id, account_id, and time. Consider partitioning transactions by time if volume is very high.
-- // on delete restrict
-- // Consider row-level security/audit logging if needed.


CREATE TABLE IF NOT EXISTS tag (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  balance bigint NOT NULL DEFAULT 0, -- cache, not source of truth
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);


-- admin can't make purchases, deposits or withdrawals
-- main_cashier can make deposits and withdrawals, not purchases
-- cashier can make purchases, not deposits, withdrawals
CREATE TABLE IF NOT EXISTS account (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type account_type NOT NULL,
  username text NOT NULL,
  password_hash text NOT NULL, -- Argon2 hash string (contains salt)
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);
CREATE UNIQUE INDEX ux_account_username_active ON account (LOWER(username)) WHERE deleted_at IS NULL;


CREATE TABLE IF NOT EXISTS account_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL REFERENCES app_account(id) ON DELETE CASCADE,
  change account_change_type NOT NULL,
  old_value text,
  new_value text,
  changed_by uuid,
  time timestamptz NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb
);


-- source of truth for the tag balance, immutable
CREATE TABLE IF NOT EXISTS transaction (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type transaction_type NOT NULL,
  -- ensure amount matches type
  amount bigint NOT NULL, -- positive -> added to balance, negative -> removed from balance, ?convention enforced by trigger?: deposits > 0; purchase/withdrawal < 0
  time timestamptz NOT NULL DEFAULT now(),
  account_id uuid NOT NULL REFERENCES account(id) ON DELETE RESTRICT,
  tag_id uuid NOT NULL REFERENCES tag(id) ON DELETE RESTRICT,
  balance_before bigint, -- filled by trigger?
  balance_after bigint, -- filled by trigger?
  metadata jsonb DEFAULT '{}'::jsonb -- keep?
);


-- maybe?
-- indexes for frequently queried columns
-- CREATE INDEX ix_transaction_tag_time ON transaction (tag_id, time DESC);
-- CREATE INDEX ix_transaction_account_time ON transaction (account_id, time DESC);


-- possibly add stuff under here:
-- permissions table (keeps mapping flexible)
-- TABLE account_type_permission {
--   id BIGINT PK // GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   // account_type account_type NOT NULL
--   // allowed_transaction transaction_type NOT NULL
--   // UNIQUE (account_type, allowed_transaction)
-- }

-- INSERT INTO account_type_permission (account_type, allowed_tx) VALUES
--   ('main_cashier','deposit') ON CONFLICT DO NOTHING,
--   ('main_cashier','withdrawal') ON CONFLICT DO NOTHING,
--   ('cashier','purchase') ON CONFLICT DO NOTHING;


-- probably make this in python
-- -- Trigger function to update tag balance and validate permissions
-- CREATE OR REPLACE FUNCTION app_transaction_before_insert()
-- RETURNS trigger
-- LANGUAGE plpgsql
-- AS $$
-- DECLARE
--   acct_type account_type;
--   allowed boolean;
--   bal_before bigint;
--   bal_after bigint;
-- BEGIN
--   -- validate account exists and get its type
--   SELECT type INTO acct_type FROM app_account WHERE id = NEW.account_id;
--   IF NOT FOUND THEN
--     RAISE EXCEPTION 'account % does not exist', NEW.account_id;
--   END IF;

--   -- check permission: is NEW.type allowed for this account type?
--   SELECT EXISTS (
--     SELECT 1 FROM account_type_permission
--     WHERE account_type = acct_type AND allowed_tx = NEW.type
--   ) INTO allowed;
--   IF NOT allowed THEN
--     RAISE EXCEPTION 'account type % not allowed to perform transaction type %', acct_type, NEW.type;
--   END IF;

--   -- enforce amount sign semantics: deposits must be >0; purchase/withdrawal must be <0
--   IF NEW.type = 'deposit' AND NEW.amount <= 0 THEN
--     RAISE EXCEPTION 'deposit amount must be > 0';
--   ELSIF (NEW.type = 'withdrawal' OR NEW.type = 'purchase') AND NEW.amount >= 0 THEN
--     RAISE EXCEPTION '% amount must be < 0', NEW.type;
--   END IF;

--   -- Lock the tag row to avoid race conditions and get its balance
--   SELECT balance INTO bal_before FROM tag WHERE id = NEW.tag_id FOR UPDATE;
--   IF NOT FOUND THEN
--     RAISE EXCEPTION 'tag % does not exist', NEW.tag_id;
--   END IF;

--   bal_after := bal_before + NEW.amount;

--   -- optional business rule: do not allow negative tag balances
--   IF bal_after < 0 THEN
--     RAISE EXCEPTION 'insufficient balance on tag % (would be %)', NEW.tag_id, bal_after;
--   END IF;

--   -- update tag balance
--   UPDATE tag SET balance = bal_after WHERE id = NEW.tag_id;

--   -- populate transaction's before/after values
--   NEW.balance_before := bal_before;
--   NEW.balance_after := bal_after;

--   RETURN NEW;
-- END;
-- $$;

-- -- Attach trigger (BEFORE INSERT so we can modify NEW and stop invalid ops)
-- CREATE TRIGGER trg_app_transaction_before_insert
-- BEFORE INSERT ON app_transaction
-- FOR EACH ROW
-- EXECUTE FUNCTION app_transaction_before_insert();
