import psycopg
from dataclasses import dataclass
from datetime import datetime
# from psycopg import sql

from pg_connection import get_connection

@dataclass
class Tag:
    id: int
    balance: int
    created_at: datetime

    def init_db():
        with get_connection() as conn:
            cur = conn.cursor()
            cur.execute("""CREATE TABLE IF NOT EXISTS tag (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        balance BIGINT NOT NULL,
                        created_at TIMESTAMP)""")
            
    def get_columns(columns=['id', 'balance', 'created_at']):
        with get_connection() as conn:
            cur = conn.cursor()
            cur.execute("""SELECT * FROM tag""")
            return cur.fetchall()
        
    def insert_rows(rows=[]):
        with get_connection() as conn:
            cur = conn.cursor()

            with conn.transaction():
                cur.executemany("""INSERT INTO tag (balance, created_at)
                                VALUES (%s, %s)""", rows)

# tag1 = Tag(1, 200, datetime(2004, 2, 25, 23, 59, 59))
Tag.init_db()
Tag.insert_rows([[2000, datetime.now()], [250, datetime.now()]])
cols = Tag.get_columns()
print(cols)